export default {
    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    // VERIFY_START: "VERIFY_START",
    // VERIFY_SUCCESS: "VERIFY_SUCCESS",
    // VERIFY_FAIL: "VERIFY_FAIL"
}