export default {
    HOME_CATEGORIES_START: 'HOME_CATEGORIES_START',
    HOME_CATEGORIES_SUCCESS: 'HOME_CATEGORIES_SUCCESS',
    HOME_SLIDERS_ITEMS_START: 'HOME_SLIDERS_ITEMS_START',
    HOME_SLIDERS_ITEMS_SUCCESS: 'HOME_SLIDERS_ITEMS_SUCCESS',
}